// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWFKC5mDptzbPtLzLuy3y7Ir2QPQ4MakU',
    appId: '1:373567202065:web:b47b0a0b3e70a65ed022b0',
    messagingSenderId: '373567202065',
    projectId: 'health-plus-94217',
    authDomain: 'health-plus-94217.firebaseapp.com',
    storageBucket: 'health-plus-94217.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0hFv3UdHDsjBnKilQJ5NtJbAhiH4Y_Qw',
    appId: '1:373567202065:android:ee4b9b8e21138d4ed022b0',
    messagingSenderId: '373567202065',
    projectId: 'health-plus-94217',
    storageBucket: 'health-plus-94217.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJjt4HoIrYmfF7WUy-Rk-FYdufb-1Cczo',
    appId: '1:373567202065:ios:27885d80e49ee8e6d022b0',
    messagingSenderId: '373567202065',
    projectId: 'health-plus-94217',
    storageBucket: 'health-plus-94217.appspot.com',
    iosBundleId: 'com.example.healthPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJjt4HoIrYmfF7WUy-Rk-FYdufb-1Cczo',
    appId: '1:373567202065:ios:27885d80e49ee8e6d022b0',
    messagingSenderId: '373567202065',
    projectId: 'health-plus-94217',
    storageBucket: 'health-plus-94217.appspot.com',
    iosBundleId: 'com.example.healthPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWFKC5mDptzbPtLzLuy3y7Ir2QPQ4MakU',
    appId: '1:373567202065:web:353367bf92f093ecd022b0',
    messagingSenderId: '373567202065',
    projectId: 'health-plus-94217',
    authDomain: 'health-plus-94217.firebaseapp.com',
    storageBucket: 'health-plus-94217.appspot.com',
  );
}
